/**
 * Build favicon + site logo PNGs from images/cc-logo-updated.png
 * Run: npm run resize-favicon
 */

import sharp from 'sharp'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..')
const SRC = path.join(ROOT, 'images/cc-logo-updated.png')
const PUBLIC = path.join(ROOT, 'public')

const BG = { r: 8, g: 9, b: 15, alpha: 1 }

/** Trim padding so the mark fills favicon squares legibly at 16–32px. */
function trimmedLogo() {
  return sharp(SRC).trim({ threshold: 24 })
}

async function writeIcon(size, name) {
  await trimmedLogo()
    .resize(size, size, { fit: 'contain', background: BG })
    .png({ compressionLevel: 9 })
    .toFile(path.join(PUBLIC, name))
  console.log(`Wrote public/${name} (${size}×${size})`)
}

async function writeLogoAtWidth(width, name) {
  await sharp(SRC)
    .resize({ width, fit: 'inside' })
    .png({ compressionLevel: 9 })
    .toFile(path.join(PUBLIC, name))
  const meta = await sharp(path.join(PUBLIC, name)).metadata()
  console.log(`Wrote public/${name} (${meta.width}×${meta.height})`)
}

async function main() {
  const meta = await sharp(SRC).metadata()
  console.log(`Source: ${SRC} (${meta.width}×${meta.height})`)

  await writeIcon(16, 'favicon-16x16.png')
  await writeIcon(32, 'favicon-32x32.png')
  await writeIcon(180, 'apple-touch-icon.png')
  await writeIcon(192, 'android-chrome-192x192.png')
  await writeIcon(512, 'android-chrome-512x512.png')

  await writeLogoAtWidth(200, 'cc-logo-header.png')
  await writeLogoAtWidth(350, 'cc-logo-footer.png')
  // OG / Twitter / SEO default (same asset as footer source size)
  await writeLogoAtWidth(350, 'cc-logo.png')

  console.log('Note: favicon.ico is not generated by this script — add/update it separately if needed.')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
